[[main]]
name = "Posts"
pageRef = "posts"
weight = 1

[[main]]
name = "Categories"
pageRef = "categories"
weight = 2

[[main]]
name = "CV"
pageRef = "cv/index.html"
weight = 3

[[footer]]
name = "Posts"
pageRef = "posts"
weight = 9

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
