[[main]]
name = "Posts"
pageRef = "posts"
weight = 1

[[main]]
name = "Tags"
pageRef = "tags"
weight = 2

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
