[[main]]
name = "Posts"
pageRef = "posts"
weight = 1

[[main]]
name = "Categories"
pageRef = "categories"
weight = 2

[[main]]
name = "CV"
url = "https://michaelhess17.github.io/cv/Michael_Hess_CV.pdf"
weight = 3

[[footer]]
name = "Posts"
pageRef = "posts"
weight = 9

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
